---
output:
  html_document: default
  word_document: default
---
```{r}
rm(list = ls())
library(readxl)
library(leaps)
library(forecast)
library(caret)
BostonHousing <- read_excel("BostonHousing.xlsx",sheet = "Data")
set.seed(1)
train.index <- createDataPartition(BostonHousing$MEDV,p = .7,list = F)
```

```{r}
#3variables
v1 <- c(1,4,6,13)
train.df <- BostonHousing[train.index,v1]
validation.df <-  BostonHousing[-train.index,v1]
mod1 <- lm(MEDV~.,train.df)
summary(mod1)
#indicates all three variables are significant with no. of rooms having the highest significance however only 55% of the variability is explained
op <- as.data.frame(cbind(.1,0,6,NA))
colnames(op) <- colnames(train.df)
predict(mod1,op)
#predicted price of given conditions would be $20,664
pred1 <- predict(mod1,validation.df)
accuracy(pred1,validation.df$MEDV)
```


```{r}
#all variables
train2.df <- BostonHousing[train.index,-14]
validation2.df <- BostonHousing[-train.index,-14]
mod2 <- lm(MEDV ~ .,train2.df)
summary(mod2)
#individually all variables except age and 
pred2 <- predict(mod2,validation2.df)
accuracy(pred2,validation2.df$MEDV)
```

```{r}
#forwardstep
forwardmod <- step(mod2,direction = "forward")
summary(forwardmod)
```


